import { TestBed } from '@angular/core/testing';
import { provideHttpClient } from '@angular/common/http';
import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';
import { FinanceService, UserPreferenceView } from './finance.service';
describe('FinanceService',()=>{
  let service:FinanceService;let http:HttpTestingController;
  beforeEach(()=>{TestBed.configureTestingModule({providers:[provideHttpClient(),provideHttpClientTesting()]});service=TestBed.inject(FinanceService);http=TestBed.inject(HttpTestingController)});
  afterEach(()=>http.verify());
  it('consulta resumo mensal no backend',()=>{service.summary(2026,8).subscribe(value=>expect(value.month).toBe(8));const request=http.expectOne('/api/v1/finance/summary?year=2026&month=8');expect(request.request.method).toBe('GET');request.flush({month:8})});
  it('solicita sugestão sem enviar userId',()=>{service.suggest('Expense','Comprar ração',null).subscribe();const request=http.expectOne('/api/v1/finance/category-suggestion');expect(request.request.method).toBe('POST');expect(request.request.body).toEqual({type:'Expense',description:'Comprar ração',notes:null});expect(request.request.body.userId).toBeUndefined();request.flush({suggestions:[]})});
  it('lista cartões e faturas',()=>{service.cards().subscribe(v=>expect(v.length).toBe(1));http.expectOne('/api/v1/finance/cards').flush([{id:'1'}]);service.invoices(2026,9).subscribe(v=>expect(v.length).toBe(1));http.expectOne('/api/v1/finance/cards/invoices?year=2026&month=9').flush([{cardId:'1'}])});
  it('lista contas e transfere entre elas',()=>{service.accounts().subscribe(v=>expect(v.length).toBe(2));http.expectOne('/api/v1/finance/accounts').flush([{id:'a'},{id:'b'}]);service.transfer('a','b',100,'2026-09-01',null).subscribe();const req=http.expectOne('/api/v1/finance/accounts/transfer');expect(req.request.body).toEqual({fromAccountId:'a',toAccountId:'b',amount:100,date:'2026-09-01',notes:null});req.flush({})});
  it('lista contas a pagar com filtro de status',()=>{service.scheduled(2026,9,'Pending').subscribe(v=>expect(v.length).toBe(1));const req=http.expectOne('/api/v1/finance/scheduled?year=2026&month=9&status=Pending');expect(req.request.method).toBe('GET');req.flush([{id:'1'}])});
  it('consulta reserva, patrimônio, calendário e relatório anual',()=>{service.reserve().subscribe();http.expectOne('/api/v1/finance/reserve').flush({});service.netWorth().subscribe();http.expectOne('/api/v1/finance/net-worth').flush({});service.calendar(2026,9).subscribe();http.expectOne('/api/v1/finance/calendar?year=2026&month=9').flush([]);service.annualReport(2026).subscribe();http.expectOne('/api/v1/finance/annual-report?year=2026').flush({})});
  it('consulta inteligência financeira V7 (entenda meu mês, resumos, insights e alertas)',()=>{service.understandMonth(2026,8).subscribe(v=>expect(v.month).toBe(8));http.expectOne('/api/v1/finance/understand-month?year=2026&month=8').flush({month:8});service.weeklySummary().subscribe();http.expectOne('/api/v1/finance/summary-weekly').flush({});service.monthlySummary(2026,8).subscribe();http.expectOne('/api/v1/finance/summary-monthly?year=2026&month=8').flush({});service.insights(2026,8).subscribe();http.expectOne('/api/v1/finance/insights?year=2026&month=8').flush([]);service.alerts().subscribe();http.expectOne('/api/v1/finance/alerts').flush([])});
  it('lê e salva preferências sem enviar userId',()=>{service.preferences().subscribe();const get=http.expectOne('/api/v1/finance/preferences');expect(get.request.method).toBe('GET');get.flush({explanationProfile:'Simple'});const body:UserPreferenceView={explanationProfile:'Detailed',alertBills:true,alertInvoices:true,alertBudget:true,alertGoals:true,alertInstallments:true,alertWeeklySummary:true,alertMonthlySummary:true};service.savePreferences(body).subscribe();const put=http.expectOne('/api/v1/finance/preferences');expect(put.request.method).toBe('PUT');expect(put.request.body).toEqual(body);expect(put.request.body.userId).toBeUndefined();put.flush(body)});
  it('envia prévia de importação como multipart e confirma sem userId',()=>{const file=new File(['data;valor\n01/08/2026;10'],'x.csv');service.importPreview(file).subscribe();const req=http.expectOne('/api/v1/finance/imports/preview');expect(req.request.method).toBe('POST');expect(req.request.body.get('file').name).toBe('x.csv');req.flush({fileName:'x.csv',total:1,duplicates:0,uncategorized:0,rows:[]});service.importConfirm([{index:1,date:'2026-08-01',description:'x',amount:10,type:'Expense',categoryId:'c1'}]).subscribe();const conf=http.expectOne('/api/v1/finance/imports/confirm');expect(conf.request.body).toEqual({rows:[{index:1,date:'2026-08-01',description:'x',amount:10,type:'Expense',categoryId:'c1'}]});expect(conf.request.body.userId).toBeUndefined();conf.flush({imported:1,skippedDuplicates:0,skippedInvalid:0})});
  it('gerencia conversas do assistente',()=>{service.conversations().subscribe();http.expectOne('/api/v1/assistant/conversations').flush([]);service.createConversation('Título').subscribe();const create=http.expectOne('/api/v1/assistant/conversations');expect(create.request.body).toEqual({title:'Título'});create.flush({id:'1'});service.conversation('1').subscribe();http.expectOne('/api/v1/assistant/conversations/1').flush([]);service.deleteConversation('1').subscribe();http.expectOne('/api/v1/assistant/conversations/1').flush({});service.clearConversations().subscribe();http.expectOne('/api/v1/assistant/conversations').flush({removed:1})});
});
