import { CurrencyPipe, DatePipe, DecimalPipe } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { FinanceService, FinancialGoal } from './finance.service';
import { FinanceNavComponent } from './finance-nav.component';

@Component({imports:[FormsModule,CurrencyPipe,DatePipe,DecimalPipe,FinanceNavComponent],template:`<section class="page finance-v5"><app-finance-nav/><span class="eyebrow">OBJETIVOS</span><h1>Metas financeiras</h1><p class="lead">Crie uma meta, registre aportes e acompanhe seu progresso.</p>
  <form class="goal-form panel" (ngSubmit)="create()"><label>Nome<input name="name" [(ngModel)]="name" maxlength="100" required placeholder="Ex.: Reserva de emergência"></label><label>Valor da meta<input name="target" [(ngModel)]="targetAmount" type="number" min="0.01" required></label><label>Prazo<input name="date" [(ngModel)]="targetDate" type="date"></label><label class="wide">Descrição<input name="description" [(ngModel)]="description" maxlength="500"></label><button class="primary">Criar meta</button></form>
  @if(error()){<p class="notice error">{{error()}}</p>}<div class="goal-list">@for(goal of goals();track goal.id){<article class="panel" [class.completed]="goal.isCompleted"><div class="goal-head"><div><h2>{{goal.name}}</h2><span>{{goal.currentAmount|currency:'BRL'}} de {{goal.targetAmount|currency:'BRL'}}</span></div><button class="link" (click)="remove(goal)">Excluir</button></div><progress [value]="goal.progressPercentage" max="100"></progress><p>{{goal.progressPercentage|number:'1.0-1'}}% @if(goal.targetDate){<span>· prazo {{goal.targetDate|date:'dd/MM/yyyy':'UTC'}}</span>}</p>@if(goal.isCompleted){<strong>Meta alcançada!</strong>}<div class="contribution"><input type="number" min="0.01" placeholder="Valor do aporte" #amount><button (click)="contribute(goal,amount)">Registrar aporte</button></div><details><summary>Histórico de aportes</summary>@for(item of goal.contributions;track item.id){<p>{{item.date|date:'dd/MM/yyyy':'UTC'}} · {{item.amount|currency:'BRL'}} {{item.description||''}}</p>}@empty{<p>Nenhum aporte registrado.</p>}</details></article>}@empty{<p class="finance-empty">Você ainda não criou metas.</p>}</div>
</section>`,styles:[`.finance-v5{max-width:1000px}.goal-form{display:grid;grid-template-columns:2fr 1fr 1fr;gap:12px;align-items:end;margin:25px 0}.goal-form input{display:block;width:100%;padding:10px;border:1px solid var(--line);border-radius:8px;margin-top:5px}.goal-form .wide{grid-column:1/3}.goal-list{display:grid;grid-template-columns:1fr 1fr;gap:14px}.goal-head{display:flex;justify-content:space-between}.goal-head h2{font-size:20px;margin-bottom:4px}.goal-list progress{width:100%;height:15px;margin-top:18px}.completed{border-color:var(--green)}.completed>strong{color:var(--green)}.contribution{display:flex;gap:8px;margin:15px 0}.contribution input{min-width:0;padding:9px;border:1px solid var(--line);border-radius:7px}.contribution button{border:0;background:var(--navy);color:var(--accent);border-radius:7px}@media(max-width:700px){.goal-form,.goal-list{grid-template-columns:1fr}.goal-form .wide{grid-column:auto}}`]})
export class FinanceGoalsComponent{
  private finance=inject(FinanceService);readonly goals=signal<FinancialGoal[]>([]);readonly error=signal('');name='';targetAmount:number|null=null;targetDate='';description='';constructor(){this.load()}
  load(){this.finance.goals().subscribe({next:x=>this.goals.set(x),error:()=>this.error.set('Não foi possível carregar as metas.')})}
  create(){if(!this.name.trim()||!this.targetAmount)return;this.finance.createGoal({name:this.name,targetAmount:this.targetAmount,currentAmount:0,targetDate:this.targetDate||null,description:this.description||null}).subscribe({next:()=>{this.name='';this.targetAmount=null;this.targetDate='';this.description='';this.load()},error:()=>this.error.set('Não foi possível criar a meta.')})}
  contribute(goal:FinancialGoal,input:HTMLInputElement){const amount=Number(input.value);if(amount<=0)return;this.finance.contribute(goal.id,amount,new Date().toISOString().slice(0,10),null).subscribe({next:()=>{input.value='';this.load()},error:()=>this.error.set('Não foi possível registrar o aporte.')})}
  remove(goal:FinancialGoal){if(confirm(`Excluir a meta “${goal.name}” e seu histórico?`))this.finance.removeGoal(goal.id).subscribe(()=>this.load())}
}
