import { CurrencyPipe, DatePipe } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Debt, FinanceService } from './finance.service';
import { FinanceNavComponent } from './finance-nav.component';

@Component({imports:[CurrencyPipe,DatePipe,FormsModule,FinanceNavComponent],template:`
<section class="page finance-page">
  <app-finance-nav/>
  <div class="finance-heading"><div><span class="eyebrow">MINHA CONTA</span><h1>Minhas dívidas</h1><p class="lead">Acompanhe o que você ainda deve e o total pendente.</p></div><button class="primary" (click)="openNew()">+ Nova dívida</button></div>
  @if(error()){<div class="notice error" role="alert">{{error()}}</div>}
  @if(total();as t){<div class="debt-total"><article class="money-card"><span>Total devido</span><strong>{{t.current|currency:'BRL':'symbol':'1.2-2'}}</strong></article><article class="money-card"><span>Total original</span><strong>{{t.original|currency:'BRL':'symbol':'1.2-2'}}</strong></article><article class="money-card balance"><span>Já pago</span><strong>{{t.paid|currency:'BRL':'symbol':'1.2-2'}}</strong></article></div>}
  @if(items();as list){<section class="panel"><div class="section-head"><div><span class="eyebrow">DÍVIDAS</span><h2>Dívidas cadastradas</h2></div></div>@for(debt of list;track debt.id){<div class="finance-row"><div><b>{{debt.name}}</b><span>{{debt.institution||'Sem instituição'}}{{debt.dueDate?' · vence '+ (debt.dueDate|date:'dd/MM/yyyy':'UTC'):''}}{{debt.installmentCount?' · '+debt.installmentCount+'x':''}}</span></div><strong>{{debt.currentAmount|currency:'BRL':'symbol':'1.2-2'}}</strong><div class="row-actions"><span class="status-badge" [class.done]="debt.isPaid">{{debt.isPaid?'Quitada':'Em aberto'}}</span><button class="link" (click)="edit(debt)">Editar</button><button class="link danger" (click)="remove(debt)">Excluir</button></div></div>}@empty{<div class="finance-empty"><p>Nenhuma dívida cadastrada.</p><button class="primary" (click)="openNew()">Adicionar dívida</button></div>}</section>}
</section>
@if(showForm()){<div class="modal-backdrop" (click)="close()"><form class="modal" (ngSubmit)="save()" (click)="$event.stopPropagation()"><h2>{{editing()?'Editar dívida':'Nova dívida'}}</h2><label>Nome<input [(ngModel)]="form.name" name="name" required maxlength="100"></label><div class="form-row"><label>Valor original<input type="number" step="0.01" min="0.01" [(ngModel)]="form.originalAmount" name="originalAmount" required></label><label>Valor atual<input type="number" step="0.01" min="0" [(ngModel)]="form.currentAmount" name="currentAmount" required></label></div><div class="form-row"><label>Nº de parcelas<input type="number" min="1" [(ngModel)]="form.installmentCount" name="installmentCount"></label><label>Juros (% a.m.)<input type="number" step="0.01" min="0" [(ngModel)]="form.interestRate" name="interestRate"></label></div><div class="form-row"><label>Vencimento<input type="date" [(ngModel)]="form.dueDate" name="dueDate"></label><label>Instituição<input [(ngModel)]="form.institution" name="institution" maxlength="100"></label></div><label>Observações<textarea [(ngModel)]="form.notes" name="notes" rows="2" maxlength="1000"></textarea></label><div class="modal-actions"><button type="button" class="ghost" (click)="close()">Cancelar</button><button class="primary" type="submit">Salvar</button></div></form></div>}`,
styles:[`.debt-total{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:18px}.money-card{border:1px solid var(--line);border-radius:14px;padding:20px;background:#fff;display:grid;gap:6px;border-top:4px solid var(--navy)}.money-card strong{font-size:24px}.balance{border-top-color:#d39b00}.finance-row{display:grid;grid-template-columns:1fr auto auto;gap:14px;align-items:center;padding:14px 0;border-bottom:1px solid var(--line)}.finance-row span{color:var(--muted)}.finance-row div{display:grid}.finance-row>strong{color:var(--danger)}.row-actions{display:flex;gap:10px;align-items:center}.status-badge{font-size:12px;font-weight:700;padding:4px 10px;border-radius:999px;background:#f3e9ef;color:var(--navy)}.status-badge.done{background:#e3f4ec;color:#168261}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.modal-backdrop{position:fixed;inset:0;background:rgba(20,10,16,.5);display:grid;place-items:center;z-index:50;padding:20px}.modal{background:#fff;border-radius:16px;padding:26px;width:min(480px,100%);max-height:90vh;overflow:auto;display:grid;gap:14px}.modal h2{margin:0}.modal label{display:grid;gap:6px;font-weight:600;color:var(--navy)}.modal input,.modal select,.modal textarea{border:1px solid var(--line);border-radius:8px;padding:10px 12px;font-size:15px;font-family:inherit}.modal-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:6px}@media(max-width:850px){.debt-total{grid-template-columns:1fr}.finance-row{grid-template-columns:1fr}.finance-row .row-actions{grid-column:1}}@media(max-width:560px){.form-row{grid-template-columns:1fr}}`]
})
export class FinanceDebtsComponent{
  private readonly finance=inject(FinanceService);
  readonly items=signal<Debt[]>([]);readonly error=signal('');readonly showForm=signal(false);readonly editing=signal<Debt|null>(null);
  readonly form={name:'',originalAmount:0,currentAmount:0,installmentCount:null as number|null,interestRate:null as number|null,dueDate:'' as string|null,institution:'',notes:''};
  constructor(){this.load()}
  load(){this.finance.debts().subscribe({next:x=>this.items.set(x),error:()=>this.error.set('Não foi possível carregar as dívidas.')})}
  total(){const list=this.items();return{current:list.filter(d=>!d.isPaid).reduce((s,d)=>s+d.currentAmount,0),original:list.reduce((s,d)=>s+d.originalAmount,0),paid:list.reduce((s,d)=>s+(d.originalAmount-d.currentAmount),0)}}
  openNew(){this.editing.set(null);this.form.name='';this.form.originalAmount=0;this.form.currentAmount=0;this.form.installmentCount=null;this.form.interestRate=null;this.form.dueDate='';this.form.institution='';this.form.notes='';this.showForm.set(true)}
  edit(debt:Debt){this.editing.set(debt);this.form.name=debt.name;this.form.originalAmount=debt.originalAmount;this.form.currentAmount=debt.currentAmount;this.form.installmentCount=debt.installmentCount;this.form.interestRate=debt.interestRate;this.form.dueDate=debt.dueDate||'';this.form.institution=debt.institution||'';this.form.notes=debt.notes||'';this.showForm.set(true)}
  close(){this.showForm.set(false)}
  save(){const body={name:this.form.name,originalAmount:this.form.originalAmount,currentAmount:this.form.currentAmount,installmentCount:this.form.installmentCount,interestRate:this.form.interestRate,dueDate:this.form.dueDate||null,institution:this.form.institution||null,notes:this.form.notes||null};const op=this.editing()?this.finance.updateDebt(this.editing()!.id,body):this.finance.createDebt(body);op.subscribe({next:()=>{this.showForm.set(false);this.load()},error:()=>this.error.set('Não foi possível salvar a dívida.')})}
  remove(debt:Debt){if(!confirm(`Excluir a dívida "${debt.name}"?`))return;this.finance.removeDebt(debt.id).subscribe({next:()=>this.load(),error:()=>this.error.set('Não foi possível excluir.')})}
}
