import { CurrencyPipe, DatePipe } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CreditCard, FinanceService, Invoice } from './finance.service';
import { FinanceNavComponent } from './finance-nav.component';

@Component({imports:[CurrencyPipe,DatePipe,FormsModule,FinanceNavComponent],template:`
<section class="page finance-page">
  <app-finance-nav/>
  <div class="finance-heading"><div><span class="eyebrow">MINHA CONTA</span><h1>Meus cartões</h1><p class="lead">Cadastre seus cartões de crédito e acompanhe as faturas.</p></div><button class="primary" (click)="openNew()">+ Novo cartão</button></div>
  @if(error()){<div class="notice error" role="alert">{{error()}}</div>}
  <div class="period" aria-label="Selecionar período"><button aria-label="Mês anterior" (click)="moveMonth(-1)">‹</button><label><span>Período</span><input type="month" [value]="monthValue" (change)="selectMonth($event)"></label><button aria-label="Próximo mês" (click)="moveMonth(1)">›</button></div>
  @if(invoices();as list){<div class="invoice-grid">@for(inv of list;track inv.cardId){<article class="invoice-card" [style.borderTopColor]="inv.cardColor||'var(--navy)'"><div class="invoice-head"><b>{{inv.cardName}}</b><span>Fatura {{inv.month}}/{{inv.year}}</span></div><strong>{{inv.value|currency:'BRL':'symbol':'1.2-2'}}</strong><div class="invoice-meta"><span>Limite usado: {{inv.limitUsed|currency:'BRL':'symbol':'1.2-2'}} de {{inv.limit|currency:'BRL':'symbol':'1.2-2'}}</span><span>Disponível: {{inv.limitAvailable|currency:'BRL':'symbol':'1.2-2'}}</span><span>Vence em {{inv.dueDate|date:'dd/MM':'UTC'}}</span><span>{{inv.transactionCount}} lançamentos</span></div></article>}@empty{<div class="finance-empty"><p>Nenhum cartão cadastrado ainda.</p><button class="primary" (click)="openNew()">Adicionar cartão</button></div>}</div>}
  @if(cards();as list){<section class="panel" style="margin-top:22px"><div class="section-head"><div><span class="eyebrow">CARTÕES</span><h2>Cartões cadastrados</h2></div></div>@for(card of list;track card.id){<div class="finance-row"><div><b>{{card.name}}</b><span>{{card.bank||'Sem banco'}} · fecha dia {{card.closingDay}} · vence dia {{card.dueDay}}{{card.last4?' · final '+card.last4:''}}</span></div><strong>{{card.limit|currency:'BRL':'symbol':'1.2-2'}}</strong><div class="row-actions"><button class="link" (click)="edit(card)">Editar</button><button class="link danger" (click)="remove(card)">Excluir</button></div></div>}@empty{<div class="finance-empty"><p>Nenhum cartão cadastrado.</p></div>}</section>}
</section>
@if(showForm()){<div class="modal-backdrop" (click)="close()"><form class="modal" (ngSubmit)="save()" (click)="$event.stopPropagation()"><h2>{{editing()?'Editar cartão':'Novo cartão'}}</h2><label>Nome do cartão<input [(ngModel)]="form.name" name="name" required maxlength="100"></label><label>Banco / instituição<input [(ngModel)]="form.bank" name="bank" maxlength="100"></label><div class="form-row"><label>Limite<input type="number" step="0.01" min="0" [(ngModel)]="form.limit" name="limit" required></label><label>Final (4 dígitos)<input [(ngModel)]="form.last4" name="last4" maxlength="4"></label></div><div class="form-row"><label>Dia de fechamento<input type="number" min="1" max="31" [(ngModel)]="form.closingDay" name="closingDay" required></label><label>Dia de vencimento<input type="number" min="1" max="31" [(ngModel)]="form.dueDay" name="dueDay" required></label></div><label>Cor (opcional)<input type="color" [(ngModel)]="form.color" name="color"></label><div class="modal-actions"><button type="button" class="ghost" (click)="close()">Cancelar</button><button class="primary" type="submit">Salvar</button></div></form></div>}`,
styles:[`.invoice-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:16px}.invoice-card{border:1px solid var(--line);border-top:4px solid var(--navy);border-radius:14px;padding:20px;background:#fff;display:grid;gap:10px}.invoice-head{display:flex;justify-content:space-between;align-items:center}.invoice-head span{color:var(--muted);font-size:13px}.invoice-card>strong{font-size:26px}.invoice-meta{display:grid;gap:4px;color:var(--muted);font-size:13px}.row-actions{display:flex;gap:10px}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.modal-backdrop{position:fixed;inset:0;background:rgba(20,10,16,.5);display:grid;place-items:center;z-index:50;padding:20px}.modal{background:#fff;border-radius:16px;padding:26px;width:min(480px,100%);max-height:90vh;overflow:auto;display:grid;gap:14px}.modal h2{margin:0}.modal label{display:grid;gap:6px;font-weight:600;color:var(--navy)}.modal input{border:1px solid var(--line);border-radius:8px;padding:10px 12px;font-size:15px}.modal-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:6px}`]
})
export class FinanceCardsComponent{
  private readonly finance=inject(FinanceService);
  readonly cards=signal<CreditCard[]>([]);readonly invoices=signal<Invoice[]>([]);readonly error=signal('');readonly showForm=signal(false);readonly editing=signal<CreditCard|null>(null);
  readonly form={name:'',bank:'',limit:0,closingDay:10,dueDay:15,last4:'',color:'#660240'};private selected=new Date();
  constructor(){this.selected.setDate(1);this.load()}
  get monthValue(){return `${this.selected.getFullYear()}-${String(this.selected.getMonth()+1).padStart(2,'0')}`}
  load(){this.finance.cards().subscribe({next:x=>this.cards.set(x),error:()=>this.error.set('Não foi possível carregar os cartões.')});this.finance.invoices(this.selected.getFullYear(),this.selected.getMonth()+1).subscribe({next:x=>this.invoices.set(x),error:()=>this.error.set('Não foi possível carregar as faturas.')})}
  moveMonth(delta:number){this.selected=new Date(this.selected.getFullYear(),this.selected.getMonth()+delta,1);this.load()}
  selectMonth(event:Event){const value=(event.target as HTMLInputElement).value;if(!value)return;const [year,month]=value.split('-').map(Number);this.selected=new Date(year,month-1,1);this.load()}
  openNew(){this.editing.set(null);this.form.name='';this.form.bank='';this.form.limit=0;this.form.closingDay=10;this.form.dueDay=15;this.form.last4='';this.form.color='#660240';this.showForm.set(true)}
  edit(card:CreditCard){this.editing.set(card);this.form.name=card.name;this.form.bank=card.bank||'';this.form.limit=card.limit;this.form.closingDay=card.closingDay;this.form.dueDay=card.dueDay;this.form.last4=card.last4||'';this.form.color=card.color||'#660240';this.showForm.set(true)}
  close(){this.showForm.set(false)}
  save(){const body={name:this.form.name,bank:this.form.bank||null,limit:this.form.limit,closingDay:this.form.closingDay,dueDay:this.form.dueDay,last4:this.form.last4||null,color:this.form.color||null};const op=this.editing()?this.finance.updateCard(this.editing()!.id,body):this.finance.createCard(body);op.subscribe({next:()=>{this.showForm.set(false);this.load()},error:()=>this.error.set('Não foi possível salvar o cartão.')})}
  remove(card:CreditCard){if(!confirm(`Excluir o cartão "${card.name}"?`))return;this.finance.removeCard(card.id).subscribe({next:()=>this.load(),error:()=>this.error.set('Não foi possível excluir o cartão.')})}
}
