import { CurrencyPipe } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { FinanceService, Reserve } from './finance.service';
import { FinanceNavComponent } from './finance-nav.component';

@Component({imports:[CurrencyPipe,FormsModule,FinanceNavComponent],template:`
<section class="page finance-page">
  <app-finance-nav/>
  <div class="finance-heading"><div><span class="eyebrow">MINHA CONTA</span><h1>Reserva de emergência</h1><p class="lead">Guarde dinheiro para imprevistos. O ideal é cobrir de 3 a 6 meses de despesas.</p></div></div>
  @if(error()){<div class="notice error" role="alert">{{error()}}</div>}
  @if(reserve();as r){<div class="reserve-card"><div class="reserve-copy"><span>Progresso da reserva</span><strong>{{r.currentAmount|currency:'BRL':'symbol':'1.2-2'}} <small>de {{r.targetAmount|currency:'BRL':'symbol':'1.2-2'}}</small></strong><p>{{r.progressPercentage}}% da meta{{r.targetMonths?' · meta de '+r.targetMonths+' meses':''}}</p></div><div class="progress"><i [style.width.%]="Math.min(100,r.progressPercentage)"></i></div><div class="reserve-actions"><button class="primary" (click)="open()">Atualizar reserva</button></div></div>}
  <section class="panel" style="margin-top:22px"><div class="section-head"><div><span class="eyebrow">PATRIMÔNIO</span><h2>Patrimônio líquido</h2></div><span>O que você possui menos o que ainda deve.</span></div>@if(netWorth();as n){<div class="networth-grid"><article class="money-card income"><span>Ativos</span><strong>{{n.assets|currency:'BRL':'symbol':'1.2-2'}}</strong><small>Contas + reserva</small></article><article class="money-card expense"><span>Passivos</span><strong>{{n.passives|currency:'BRL':'symbol':'1.2-2'}}</strong><small>Dívidas em aberto</small></article><article class="money-card balance"><span>Patrimônio líquido</span><strong>{{n.netWorth|currency:'BRL':'symbol':'1.2-2'}}</strong><small>{{n.netWorth>=0?'Positivo':'Negativo'}}</small></article></div>@for(acc of n.accounts;track acc.id){<div class="finance-row"><div><b>{{acc.name}}</b><span>Conta</span></div><strong>{{acc.balance|currency:'BRL':'symbol':'1.2-2'}}</strong></div>}}@else{<div class="finance-empty"><p>Cadastre contas e dívidas para ver seu patrimônio.</p></div>}</section>
</section>
@if(showForm()){<div class="modal-backdrop" (click)="close()"><form class="modal" (ngSubmit)="save()" (click)="$event.stopPropagation()"><h2>Atualizar reserva</h2><div class="form-row"><label>Meta (R$)<input type="number" step="0.01" min="0.01" [(ngModel)]="form.targetAmount" name="targetAmount" required></label><label>Valor atual (R$)<input type="number" step="0.01" min="0" [(ngModel)]="form.currentAmount" name="currentAmount" required></label></div><label>Meta em meses (opcional)<input type="number" min="1" [(ngModel)]="form.targetMonths" name="targetMonths"></label><label>Observações<textarea [(ngModel)]="form.notes" name="notes" rows="2" maxlength="1000"></textarea></label><div class="modal-actions"><button type="button" class="ghost" (click)="close()">Cancelar</button><button class="primary" type="submit">Salvar</button></div></form></div>}`,
styles:[`.reserve-card{border:1px solid var(--line);border-radius:16px;padding:26px;background:linear-gradient(115deg,#fff9cf,#fffafd);display:grid;gap:16px}.reserve-copy span{color:var(--muted);font-weight:600}.reserve-copy strong{font-size:30px;color:var(--navy)}.reserve-copy small{font-size:16px;color:var(--muted)}.reserve-copy p{color:var(--muted);margin:4px 0 0}.progress{height:14px;background:#f3e9ef;border-radius:999px;overflow:hidden}.progress i{display:block;height:100%;background:linear-gradient(90deg,#168261,#2bb673);border-radius:999px}.reserve-actions{display:flex;justify-content:flex-end}.networth-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:14px}.money-card{border:1px solid var(--line);border-radius:14px;padding:20px;background:#fff;display:grid;gap:6px;border-top:4px solid var(--navy)}.money-card strong{font-size:24px}.money-card small{color:var(--muted)}.income{border-top-color:#168261}.expense{border-top-color:#a63434}.balance{border-top-color:#d39b00}.finance-row{display:grid;grid-template-columns:1fr auto;gap:14px;align-items:center;padding:12px 0;border-bottom:1px solid var(--line)}.finance-row span{color:var(--muted)}.finance-row div{display:grid}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.modal-backdrop{position:fixed;inset:0;background:rgba(20,10,16,.5);display:grid;place-items:center;z-index:50;padding:20px}.modal{background:#fff;border-radius:16px;padding:26px;width:min(480px,100%);max-height:90vh;overflow:auto;display:grid;gap:14px}.modal h2{margin:0}.modal label{display:grid;gap:6px;font-weight:600;color:var(--navy)}.modal input,.modal textarea{border:1px solid var(--line);border-radius:8px;padding:10px 12px;font-size:15px;font-family:inherit}.modal-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:6px}@media(max-width:850px){.networth-grid{grid-template-columns:1fr}}@media(max-width:560px){.form-row{grid-template-columns:1fr}}`]
})
export class FinanceReserveComponent{
  private readonly finance=inject(FinanceService);
  readonly reserve=signal<Reserve|null>(null);readonly netWorth=signal<{assets:number;passives:number;netWorth:number;accounts:{id:string;name:string;balance:number}[]}|null>(null);readonly error=signal('');readonly showForm=signal(false);
  readonly form={targetAmount:0,currentAmount:0,targetMonths:null as number|null,notes:''};readonly Math=Math;
  constructor(){this.load()}
  load(){this.finance.reserve().subscribe({next:x=>this.reserve.set(x),error:()=>this.error.set('Não foi possível carregar a reserva.')});this.finance.netWorth().subscribe({next:x=>this.netWorth.set({assets:x.assets,passives:x.passives,netWorth:x.netWorth,accounts:x.accounts}),error:()=>{}})}
  open(){const r=this.reserve();this.form.targetAmount=r?.targetAmount||0;this.form.currentAmount=r?.currentAmount||0;this.form.targetMonths=r?.targetMonths||null;this.form.notes=r?.notes||'';this.showForm.set(true)}
  close(){this.showForm.set(false)}
  save(){this.finance.saveReserve({targetAmount:this.form.targetAmount,currentAmount:this.form.currentAmount,targetMonths:this.form.targetMonths,notes:this.form.notes||null}).subscribe({next:()=>{this.showForm.set(false);this.load()},error:()=>this.error.set('Não foi possível salvar a reserva.')})}
}
