import { CurrencyPipe, DatePipe } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { FinanceCategory, FinanceService, FinanceSummary, ScheduledStatus, ScheduledTransaction, TransactionType } from './finance.service';
import { FinanceNavComponent } from './finance-nav.component';

const STATUS_LABELS:Record<ScheduledStatus,string>={Pending:'Pendente',Paid:'Pago',Received:'Recebido'};

@Component({imports:[CurrencyPipe,DatePipe,FormsModule,FinanceNavComponent],template:`
<section class="page finance-page">
  <app-finance-nav/>
  <div class="finance-heading"><div><span class="eyebrow">MINHA CONTA</span><h1>Contas a pagar e receber</h1><p class="lead">Planeje o que vai entrar e sair. Marque como pago/recebido quando acontecer.</p></div><button class="primary" (click)="openNew()">+ Nova conta</button></div>
  @if(error()){<div class="notice error" role="alert">{{error()}}</div>}
  <div class="period" aria-label="Selecionar período"><button aria-label="Mês anterior" (click)="moveMonth(-1)">‹</button><label><span>Período</span><input type="month" [value]="monthValue" (change)="selectMonth($event)"></label><button aria-label="Próximo mês" (click)="moveMonth(1)">›</button></div>
  @if(planned();as p){<div class="planned-stats"><article class="money-card"><span>Previsto (entradas)</span><strong>{{p.expectedIncome|currency:'BRL':'symbol':'1.2-2'}}</strong></article><article class="money-card"><span>Previsto (saídas)</span><strong>{{p.expectedExpenses|currency:'BRL':'symbol':'1.2-2'}}</strong></article><article class="money-card balance"><span>Previsto (sobra)</span><strong>{{p.expectedBalance|currency:'BRL':'symbol':'1.2-2'}}</strong></article></div>}
  @if(realized();as r){<div class="planned-stats"><article class="money-card income"><span>Realizado (entradas)</span><strong>{{r.totalIncome|currency:'BRL':'symbol':'1.2-2'}}</strong></article><article class="money-card expense"><span>Realizado (saídas)</span><strong>{{r.totalExpenses|currency:'BRL':'symbol':'1.2-2'}}</strong></article><article class="money-card balance"><span>Realizado (sobra)</span><strong>{{r.balance|currency:'BRL':'symbol':'1.2-2'}}</strong></article></div>}
  <div class="filter-tabs"><button [class.active]="!statusFilter()" (click)="setFilter(null)">Todas</button><button [class.active]="statusFilter()==='Pending'" (click)="setFilter('Pending')">Pendentes</button><button [class.active]="statusFilter()==='Paid'" (click)="setFilter('Paid')">Pagas</button><button [class.active]="statusFilter()==='Received'" (click)="setFilter('Received')">Recebidas</button></div>
  @if(items();as list){<section class="panel"><div class="section-head"><div><span class="eyebrow">LANÇAMENTOS PREVISTOS</span><h2>Contas do mês</h2></div></div>@for(item of list;track item.id){<div class="finance-row"><time>{{item.dueDate|date:'dd/MM':'UTC'}}</time><div><b>{{item.description}}</b><span>{{item.categoryName}}{{item.accountName?' · '+item.accountName:''}}</span></div><strong [class.income-value]="item.type==='Income'">{{item.type==='Income'?'+':'−'}} {{item.amount|currency:'BRL':'symbol':'1.2-2'}}</strong><div class="row-actions"><span class="status-badge" [class.done]="item.status!=='Pending'">{{STATUS_LABELS[item.status]}}</span><button class="link" (click)="toggleStatus(item)">{{item.status==='Pending'?(item.type==='Income'?'Receber':'Pagar'):'Reverter'}}</button><button class="link" (click)="edit(item)">Editar</button><button class="link danger" (click)="remove(item)">Excluir</button></div></div>}@empty{<div class="finance-empty"><p>Nenhuma conta prevista para este mês.</p><button class="primary" (click)="openNew()">Adicionar conta</button></div>}</section>}
</section>
@if(showForm()){<div class="modal-backdrop" (click)="close()"><form class="modal" (ngSubmit)="save()" (click)="$event.stopPropagation()"><h2>{{editing()?'Editar conta':'Nova conta'}}</h2><label>Tipo<select [(ngModel)]="form.type" name="type"><option value="Expense">Saída (a pagar)</option><option value="Income">Entrada (a receber)</option></select></label><label>Descrição<input [(ngModel)]="form.description" name="description" required maxlength="160"></label><label>Categoria<select [(ngModel)]="form.categoryId" name="categoryId" required><option [ngValue]="null" disabled>Escolha</option>@for(cat of categoriesForType();track cat.id){<option [ngValue]="cat.id">{{cat.name}}</option>}</select></label><div class="form-row"><label>Valor<input type="number" step="0.01" min="0.01" [(ngModel)]="form.amount" name="amount" required></label><label>Vencimento<input type="date" [(ngModel)]="form.dueDate" name="dueDate" required></label></div><label>Conta (opcional)<select [(ngModel)]="form.accountId" name="accountId"><option [ngValue]="null">Sem conta</option>@for(acc of accounts();track acc.id){<option [ngValue]="acc.id">{{acc.name}}</option>}</select></label><div class="modal-actions"><button type="button" class="ghost" (click)="close()">Cancelar</button><button class="primary" type="submit">Salvar</button></div></form></div>}`,
styles:[`.planned-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:18px}.money-card{border:1px solid var(--line);border-radius:14px;padding:20px;background:#fff;display:grid;gap:6px;border-top:4px solid var(--navy)}.money-card strong{font-size:24px}.income{border-top-color:#168261}.expense{border-top-color:#a63434}.balance{border-top-color:#d39b00}.filter-tabs{display:flex;gap:8px;margin-bottom:18px;flex-wrap:wrap}.filter-tabs button{padding:8px 14px;border:1px solid var(--line);border-radius:999px;background:#fff;color:var(--navy);cursor:pointer}.filter-tabs button.active{background:var(--navy);color:var(--accent);border-color:var(--navy)}.finance-row{display:grid;grid-template-columns:58px 1fr auto auto;gap:14px;align-items:center;padding:14px 0;border-bottom:1px solid var(--line)}.finance-row time,.finance-row span{color:var(--muted)}.finance-row div{display:grid}.finance-row>strong{color:var(--danger)}.finance-row>strong.income-value{color:var(--green)}.row-actions{display:flex;gap:10px;align-items:center}.status-badge{font-size:12px;font-weight:700;padding:4px 10px;border-radius:999px;background:#f3e9ef;color:var(--navy)}.status-badge.done{background:#e3f4ec;color:#168261}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.modal-backdrop{position:fixed;inset:0;background:rgba(20,10,16,.5);display:grid;place-items:center;z-index:50;padding:20px}.modal{background:#fff;border-radius:16px;padding:26px;width:min(480px,100%);max-height:90vh;overflow:auto;display:grid;gap:14px}.modal h2{margin:0}.modal label{display:grid;gap:6px;font-weight:600;color:var(--navy)}.modal input,.modal select{border:1px solid var(--line);border-radius:8px;padding:10px 12px;font-size:15px}.modal-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:6px}@media(max-width:850px){.planned-stats{grid-template-columns:1fr}.finance-row{grid-template-columns:45px 1fr}.finance-row>strong,.finance-row .row-actions{grid-column:2}}@media(max-width:560px){.form-row{grid-template-columns:1fr}}`]
})
export class FinanceScheduledComponent{
  private readonly finance=inject(FinanceService);
  readonly items=signal<ScheduledTransaction[]>([]);readonly categories=signal<FinanceCategory[]>([]);readonly accounts=signal<{id:string;name:string}[]>([]);readonly planned=signal<{expectedIncome:number;expectedExpenses:number;expectedBalance:number}|null>(null);readonly realized=signal<FinanceSummary|null>(null);readonly error=signal('');readonly showForm=signal(false);readonly editing=signal<ScheduledTransaction|null>(null);readonly statusFilter=signal<ScheduledStatus|null>(null);readonly STATUS_LABELS=STATUS_LABELS;
  readonly form={type:'Expense' as TransactionType,categoryId:null as string|null,description:'',amount:0,dueDate:new Date().toISOString().slice(0,10),accountId:null as string|null};private selected=new Date();
  constructor(){this.selected.setDate(1);this.finance.categories().subscribe({next:x=>this.categories.set(x),error:()=>this.error.set('Não foi possível carregar as categorias.')});this.finance.accounts().subscribe({next:x=>this.accounts.set(x.map(a=>({id:a.id,name:a.name}))),error:()=>{}});this.load()}
  get monthValue(){return `${this.selected.getFullYear()}-${String(this.selected.getMonth()+1).padStart(2,'0')}`}
  load(){const y=this.selected.getFullYear(),m=this.selected.getMonth()+1;this.finance.scheduled(y,m,this.statusFilter()||undefined).subscribe({next:x=>this.items.set(x),error:()=>this.error.set('Não foi possível carregar as contas.')});this.finance.forecast(y,m).subscribe({next:x=>this.planned.set({expectedIncome:x.expectedIncome,expectedExpenses:x.expectedExpenses,expectedBalance:x.expectedBalance}),error:()=>{}});this.finance.summary(y,m).subscribe({next:x=>this.realized.set(x),error:()=>{}})}
  moveMonth(delta:number){this.selected=new Date(this.selected.getFullYear(),this.selected.getMonth()+delta,1);this.load()}
  selectMonth(event:Event){const value=(event.target as HTMLInputElement).value;if(!value)return;const [year,month]=value.split('-').map(Number);this.selected=new Date(year,month-1,1);this.load()}
  setFilter(status:ScheduledStatus|null){this.statusFilter.set(status);this.load()}
  categoriesForType(){return this.categories().filter(c=>c.type===this.form.type)}
  openNew(){this.editing.set(null);this.form.type='Expense';this.form.categoryId=null;this.form.description='';this.form.amount=0;this.form.dueDate=new Date().toISOString().slice(0,10);this.form.accountId=null;this.showForm.set(true)}
  edit(item:ScheduledTransaction){this.editing.set(item);this.form.type=item.type;this.form.categoryId=item.categoryId;this.form.description=item.description;this.form.amount=item.amount;this.form.dueDate=item.dueDate;this.form.accountId=item.accountId;this.showForm.set(true)}
  close(){this.showForm.set(false)}
  save(){if(!this.form.categoryId){this.error.set('Escolha uma categoria.');return}const body={type:this.form.type,categoryId:this.form.categoryId,description:this.form.description,amount:this.form.amount,dueDate:this.form.dueDate,accountId:this.form.accountId,notes:null};const op=this.editing()?this.finance.updateScheduled(this.editing()!.id,body):this.finance.createScheduled(body);op.subscribe({next:()=>{this.showForm.set(false);this.load()},error:()=>this.error.set('Não foi possível salvar a conta.')})}
  remove(item:ScheduledTransaction){if(!confirm(`Excluir "${item.description}"?`))return;this.finance.removeScheduled(item.id).subscribe({next:()=>this.load(),error:()=>this.error.set('Não foi possível excluir.')})}
  toggleStatus(item:ScheduledTransaction){const next=item.status==='Pending'?(item.type==='Income'?'Received':'Paid'):'Pending';this.finance.setScheduledStatus(item.id,next as ScheduledStatus).subscribe({next:()=>this.load(),error:()=>this.error.set('Não foi possível atualizar o status.')})}
}
