import { CurrencyPipe, DatePipe } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { CreditCard, FinanceCategory, FinanceService, FinanceTransaction, FinancialAccount, PAYMENT_LABELS, PaymentMethod, TransactionType } from './finance.service';
import { TransactionFormComponent } from './transaction-form.component';

@Component({imports:[CurrencyPipe,DatePipe,FormsModule,RouterLink,TransactionFormComponent],template:`
<section class="page transactions-page"><a class="back" routerLink="/minha-conta/financas">← Voltar ao dashboard</a><div class="finance-heading"><div><span class="eyebrow">CONTROLE FINANCEIRO</span><h1>Lançamentos</h1><p class="lead">Consulte, filtre e mantenha seu histórico financeiro.</p></div><button class="primary" (click)="openCreate()">+ Novo lançamento</button></div>
  <section class="filters panel" aria-label="Filtros"><label>Mês<input type="month" [(ngModel)]="period" (change)="page=1;load()"></label><label>Tipo<select [(ngModel)]="type" (change)="page=1;load()"><option value="">Todos</option><option value="Income">Entradas</option><option value="Expense">Saídas</option></select></label><label>Categoria<select [(ngModel)]="categoryId" (change)="page=1;load()"><option value="">Todas</option>@for(item of categories();track item.id){<option [value]="item.id">{{item.name}}</option>}</select></label><label>Pagamento<select [(ngModel)]="paymentMethod" (change)="page=1;load()"><option value="">Todos</option>@for(option of paymentOptions;track option[0]){<option [value]="option[0]">{{option[1]}}</option>}</select></label><label>Valor mínimo<input type="number" min="0" [(ngModel)]="minAmount"></label><label>Valor máximo<input type="number" min="0" [(ngModel)]="maxAmount"></label><label class="filter-search">Descrição ou observação<input [(ngModel)]="search" (keyup.enter)="page=1;load()" placeholder="Pesquisar"><button (click)="page=1;load()">Buscar</button></label></section>
  <div class="export-row"><button (click)="clearFilters()">Limpar filtros</button> <button (click)="exportCurrent()">Exportar filtros para Excel</button></div>
  @if(error()){<div class="notice error" role="alert">{{error()}}</div>}
  @if(loading()){<p class="notice" role="status">Carregando lançamentos…</p>}@else{
    <div class="transaction-list">@for(item of items();track item.id){<article class="transaction-item" [class.income]="item.type==='Income'"><time>{{item.transactionDate|date:'dd/MM/yyyy':'UTC'}}</time><div><b>{{item.description}} @if(item.installmentNumber){<small>· parcela {{item.installmentNumber}}/{{item.installmentCount}}</small>}</b><span>{{item.categoryName}} · {{paymentLabels[item.paymentMethod]}}</span>@if(item.isRecurring){<small>Recorrente mensal</small>}</div><strong><span class="sr-only">{{item.type==='Income'?'Entrada':'Saída'}}:</span>{{item.type==='Income'?'+':'−'}} {{item.amount|currency:'BRL':'symbol':'1.2-2'}}</strong><div class="row-actions"><button aria-label="Editar lançamento" (click)="edit(item)">Editar</button><button aria-label="Excluir lançamento" (click)="remove(item)">Excluir</button></div></article>}@empty{<div class="finance-empty"><p>Nenhum lançamento encontrado para os filtros selecionados.</p><button class="primary" (click)="openCreate()">Adicionar lançamento</button></div>}</div>
    @if(total()>pageSize){<nav class="pagination" aria-label="Paginação"><button [disabled]="page===1" (click)="page=page-1;load()">Anterior</button><span>Página {{page}} de {{pageCount}}</span><button [disabled]="page>=pageCount" (click)="page=page+1;load()">Próxima</button></nav>}
  }
  <details class="category-manager panel"><summary>Minhas categorias personalizadas</summary><div class="new-category"><input [(ngModel)]="newCategoryName" maxlength="80" placeholder="Nome da categoria" aria-label="Nome da nova categoria"><select [(ngModel)]="newCategoryType" aria-label="Tipo da nova categoria"><option value="Expense">Saída</option><option value="Income">Entrada</option></select><button class="primary" (click)="createCategory()">Adicionar</button></div>@for(category of customCategories;track category.id){<div class="custom-category"><span>{{category.name}} · {{category.type==='Income'?'Entrada':'Saída'}}</span><div><button (click)="renameCategory(category)">Renomear</button><button (click)="deleteCategory(category)">Excluir</button></div></div>}@empty{<p>Você ainda não criou categorias próprias.</p>}</details>
</section>
@if(formOpen()){<app-transaction-form [categories]="categories()" [cards]="cards()" [accounts]="accounts()" [transaction]="editing()" (cancel)="formOpen.set(false)" (saved)="afterSaved()"/>}`,
styles:[`.transactions-page{max-width:1120px}.back{display:inline-block;color:var(--blue);margin-bottom:24px}.finance-heading{display:flex;justify-content:space-between;align-items:end;gap:20px}.filters{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:28px 0}.filters label{margin:0}.filters input,.filters select{display:block;width:100%;padding:10px;margin-top:5px;border:1px solid var(--line);border-radius:8px;background:#fff}.filter-search{grid-column:1/-1;display:grid;grid-template-columns:1fr auto;align-items:end}.filter-search input{grid-column:1}.filter-search button{grid-column:2;grid-row:1/3;padding:11px 18px;border:0;border-radius:8px;background:var(--navy);color:var(--accent)}.transaction-list{display:grid;gap:10px}.transaction-item{display:grid;grid-template-columns:90px 1fr auto auto;align-items:center;gap:18px;border:1px solid var(--line);border-left:5px solid var(--danger);border-radius:10px;padding:16px;background:#fff}.transaction-item.income{border-left-color:var(--green)}.transaction-item>div:nth-child(2){display:grid}.transaction-item span,.transaction-item small,.transaction-item time{color:var(--muted)}.transaction-item>strong{color:var(--danger)}.transaction-item.income>strong{color:var(--green)}.row-actions{display:flex;gap:6px}.row-actions button,.custom-category button,.pagination button{border:1px solid var(--line);background:#fff;border-radius:7px;padding:7px;cursor:pointer}.finance-empty{text-align:center;padding:50px}.pagination{display:flex;justify-content:center;gap:15px;align-items:center;margin:24px}.category-manager{margin-top:35px}.category-manager summary{font-weight:800;cursor:pointer}.new-category{display:grid;grid-template-columns:1fr 160px auto;gap:10px;margin:20px 0}.new-category input,.new-category select{padding:10px;border:1px solid var(--line);border-radius:8px}.custom-category{display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid var(--line)}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}@media(max-width:760px){.finance-heading{align-items:start;flex-direction:column}.filters{grid-template-columns:1fr 1fr}.transaction-item{grid-template-columns:1fr auto}.transaction-item time{grid-column:1}.transaction-item>div:nth-child(2){grid-column:1}.transaction-item>strong{grid-column:2;grid-row:1/3}.row-actions{grid-column:1/-1}.new-category{grid-template-columns:1fr}.filter-search{grid-column:1/-1}}`]
})
export class FinanceTransactionsComponent{
  private readonly finance=inject(FinanceService);readonly categories=signal<FinanceCategory[]>([]);readonly cards=signal<CreditCard[]>([]);readonly accounts=signal<FinancialAccount[]>([]);readonly items=signal<FinanceTransaction[]>([]);readonly total=signal(0);readonly loading=signal(false);readonly error=signal('');readonly formOpen=signal(false);readonly editing=signal<FinanceTransaction|null>(null);readonly paymentOptions=Object.entries(PAYMENT_LABELS) as [PaymentMethod,string][];readonly paymentLabels=PAYMENT_LABELS;
  period=currentMonth();type:''|TransactionType='';categoryId='';paymentMethod:''|PaymentMethod='';search='';minAmount:number|null=null;maxAmount:number|null=null;page=1;readonly pageSize=20;newCategoryName='';newCategoryType:TransactionType='Expense';
  constructor(){this.refreshCategories();this.load();this.finance.cards().subscribe({next:x=>this.cards.set(x),error:()=>{}});this.finance.accounts().subscribe({next:x=>this.accounts.set(x),error:()=>{}})}
  get pageCount(){return Math.max(1,Math.ceil(this.total()/this.pageSize))}get customCategories(){return this.categories().filter(x=>x.isCustom)}
  load(){this.loading.set(true);this.error.set('');const [year,month]=this.period.split('-').map(Number);this.finance.transactions({year,month,type:this.type||undefined,categoryId:this.categoryId||undefined,paymentMethod:this.paymentMethod||undefined,search:this.search.trim()||undefined,minAmount:this.minAmount??undefined,maxAmount:this.maxAmount??undefined,page:this.page,pageSize:this.pageSize}).subscribe({next:x=>{this.items.set(x.items);this.total.set(x.total);this.loading.set(false)},error:()=>{this.loading.set(false);this.error.set('Não foi possível carregar os lançamentos.')}})}
  exportCurrent(){const [year,month]=this.period.split('-').map(Number);this.finance.exportExcel({year,month,type:this.type||undefined,categoryId:this.categoryId||undefined,paymentMethod:this.paymentMethod||undefined,search:this.search.trim()||undefined,minAmount:this.minAmount??undefined,maxAmount:this.maxAmount??undefined}).subscribe(blob=>{const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`controle-financeiro-${this.period}.xlsx`;anchor.click();URL.revokeObjectURL(url)})}
  clearFilters(){this.period=currentMonth();this.type='';this.categoryId='';this.paymentMethod='';this.search='';this.minAmount=null;this.maxAmount=null;this.page=1;this.load()}
  openCreate(){this.editing.set(null);this.formOpen.set(true)}edit(item:FinanceTransaction){this.editing.set(item);this.formOpen.set(true)}afterSaved(){this.formOpen.set(false);this.load();this.refreshCategories()}
  remove(item:FinanceTransaction){if(!window.confirm('Tem certeza que deseja excluir este lançamento?'))return;this.finance.remove(item.id).subscribe({next:()=>this.load(),error:()=>this.error.set('Não foi possível excluir o lançamento.')})}
  createCategory(){const name=this.newCategoryName.trim();if(!name)return;this.finance.createCategory(name,this.newCategoryType).subscribe({next:()=>{this.newCategoryName='';this.refreshCategories()},error:e=>this.error.set(e.error?.title??'Não foi possível criar a categoria.')})}
  renameCategory(category:FinanceCategory){const name=window.prompt('Novo nome da categoria:',category.name)?.trim();if(!name)return;this.finance.updateCategory(category.id,name,category.type).subscribe({next:()=>this.refreshCategories(),error:()=>this.error.set('Não foi possível alterar a categoria.')})}
  deleteCategory(category:FinanceCategory){if(!window.confirm('Tem certeza que deseja excluir esta categoria?'))return;this.finance.removeCategory(category.id).subscribe({next:()=>this.refreshCategories(),error:()=>this.error.set('Não foi possível excluir a categoria.')})}
  private refreshCategories(){this.finance.categories().subscribe({next:x=>this.categories.set(x),error:()=>this.error.set('Não foi possível carregar as categorias.')})}
}
function currentMonth(){const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`}
