import { CurrencyPipe, DecimalPipe } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { FinanceService, MonthlyReport } from './finance.service';
import { FinanceNavComponent } from './finance-nav.component';

@Component({imports:[FormsModule,CurrencyPipe,DecimalPipe,FinanceNavComponent],template:`<section class="page finance-v5"><app-finance-nav/><div class="heading"><div><span class="eyebrow">ANÁLISE</span><h1>Relatório mensal</h1><p class="lead">Um resumo simples do seu mês, com alertas e dados exportáveis.</p></div><button class="primary" (click)="export()">Exportar Excel</button></div><label class="period">Mês<input type="month" [(ngModel)]="period" (change)="load()"></label>
  @if(report();as data){<div class="stats"><article class="panel"><span>Entradas</span><b>{{data.totalIncome|currency:'BRL'}}</b></article><article class="panel"><span>Saídas</span><b>{{data.totalExpenses|currency:'BRL'}}</b></article><article class="panel"><span>Quanto sobrou</span><b>{{data.balance|currency:'BRL'}}</b></article><article class="panel"><span>Taxa de economia</span><b>{{data.savingsRate===null?'—':(data.savingsRate|number:'1.0-1')+'%'}}</b></article></div><section class="panel insight"><h2>Leitura do mês</h2><p>{{data.insight}}</p>@if(data.largestExpenseCategory){<p>Maior categoria de saída: <b>{{data.largestExpenseCategory.categoryName}}</b> ({{data.largestExpenseCategory.amount|currency:'BRL'}}).</p>}</section>@if(data.alerts.length){<section class="alerts"><h2>Alertas</h2>@for(alert of data.alerts;track alert){<p>⚠ {{alert}}</p>}</section>}<details class="panel"><summary>Como estes números são calculados?</summary><p>Entradas menos saídas formam o saldo. A taxa de economia divide o saldo pelas entradas do período. Parcelas e recorrências entram no mês de sua data prevista.</p></details>}
</section>`,styles:[`.finance-v5{max-width:1050px}.heading{display:flex;justify-content:space-between;align-items:end;gap:20px}.period{display:block;width:220px;margin:24px 0}.period input{display:block;width:100%;padding:10px;border:1px solid var(--line);border-radius:8px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.stats article{display:grid}.stats b{font-size:22px}.insight{margin:18px 0}.alerts{background:#fff3e4;border-left:4px solid #c97800;padding:14px 20px;margin:18px 0}@media(max-width:760px){.heading{align-items:start;flex-direction:column}.stats{grid-template-columns:1fr 1fr}}@media(max-width:440px){.stats{grid-template-columns:1fr}}`]})
export class FinanceReportComponent{
  private finance=inject(FinanceService);readonly report=signal<MonthlyReport|null>(null);period=currentMonth();constructor(){this.load()}
  load(){const [year,month]=this.period.split('-').map(Number);this.finance.report(year,month).subscribe(x=>this.report.set(x))}
  export(){const [year,month]=this.period.split('-').map(Number);this.finance.exportExcel({year,month}).subscribe(blob=>{const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`controle-financeiro-${this.period}.xlsx`;anchor.click();URL.revokeObjectURL(url)})}
}
function currentMonth(){const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`}
