import { HttpClient } from '@angular/common/http'; import { Component, computed, inject, input, signal } from '@angular/core'; import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms'; import { CurrencyPipe } from '@angular/common';
interface Response{result:number;breakdown:Record<string,number>;formula:string;steps:string[];rule:{name:string;version:string;validFrom:string;validUntil:string|null;source:string|null}}
@Component({imports:[ReactiveFormsModule,CurrencyPipe],template:`<section class="page narrow"><a href="/">← Voltar às ferramentas</a><span class="eyebrow">CALCULADORA AUDITÁVEL</span><h1>{{title()}}</h1><p>{{description()}}</p><div class="calculator-grid"><form class="panel" [formGroup]="form" (ngSubmit)="calculate()">
@if(slug()==='juros-compostos'){<label>Capital inicial (R$)<input type="number" formControlName="initialCapital"></label><label>Taxa mensal (%)<input type="number" step="0.01" formControlName="monthlyRatePercent"></label><label>Período (meses)<input type="number" formControlName="months"></label><label>Aporte mensal (opcional)<input type="number" formControlName="monthlyContribution"></label>}
@if(slug()==='ferias'){<label>Salário bruto (R$)<input type="number" formControlName="grossSalary"></label><label>Dias de férias<input type="number" formControlName="vacationDays"></label><label class="check"><input type="checkbox" formControlName="sellOneThird"> Vender 1/3 das férias</label>}
@if(slug()==='decimo-terceiro'){<label>Salário (R$)<input type="number" formControlName="salary"></label><label>Meses trabalhados<input type="number" formControlName="monthsWorked"></label>}
<button class="primary" [disabled]="form.invalid||loading()">{{loading()?'Calculando…':'Calcular'}}</button>@if(error()){<p class="error">{{error()}}</p>}</form>
<aside class="result" aria-live="polite">@if(result();as r){<span class="eyebrow">RESULTADO ESTIMADO</span><strong>{{r.result|currency:'BRL'}}</strong><h2>Detalhamento</h2>@for(item of entries(r.breakdown);track item[0]){<div class="line"><span>{{label(item[0])}}</span><b>{{item[1]|currency:'BRL'}}</b></div>}<h2>Como calculamos?</h2><code>{{r.formula}}</code>@for(step of r.steps;track step){<p>• {{step}}</p>}<div class="rule"><b>Regra utilizada</b><span>{{r.rule.name}}</span><span>Versão: {{r.rule.version}}</span><span>Vigência: {{r.rule.validFrom}} — {{r.rule.validUntil||'em aberto'}}</span><span>Fonte: {{r.rule.source||'pendente de validação oficial'}}</span></div>}@else{<div class="empty">Preencha os campos para ver o resultado, detalhamento e regra utilizada.</div>}</aside></div></section>`})
export class CalculatorComponent{
 private http=inject(HttpClient);private fb=inject(FormBuilder);slug=input.required<string>();loading=signal(false);error=signal('');result=signal<Response|null>(null);
 title=computed(()=>({ferias:'Calculadora de férias','decimo-terceiro':'Calculadora de 13º salário','juros-compostos':'Calculadora de juros compostos'}[this.slug()]??'Calculadora'));
 description=computed(()=>this.slug()==='juros-compostos'?'Projete a evolução do capital com aportes ao final de cada mês.':'Estimativa bruta para fins educacionais; casos específicos exigem validação profissional.');
 form=this.fb.group({initialCapital:[1000,[Validators.required,Validators.min(0)]],monthlyRatePercent:[1,[Validators.required,Validators.min(0)]],months:[12,[Validators.required,Validators.min(1),Validators.max(1200)]],monthlyContribution:[0,[Validators.min(0)]],grossSalary:[3000,[Validators.required,Validators.min(0.01)]],vacationDays:[30,[Validators.required,Validators.min(1),Validators.max(30)]],sellOneThird:[false],salary:[3000,[Validators.required,Validators.min(0.01)]],monthsWorked:[12,[Validators.required,Validators.min(1),Validators.max(12)]]});
 calculate(){if(this.form.invalid)return;this.loading.set(true);this.error.set('');const endpoints:Record<string,string>={ferias:'vacation','decimo-terceiro':'thirteenth-salary','juros-compostos':'compound-interest'};this.http.post<Response>(`/api/v1/calculations/${endpoints[this.slug()]}`,this.form.getRawValue()).subscribe({next:r=>{this.result.set(r);this.loading.set(false)},error:e=>{this.error.set(e.error?.detail??'Não foi possível calcular.');this.loading.set(false)}})}
 entries(v:Record<string,number>){return Object.entries(v)} label(v:string){return v.replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase())}
}
