using CentralContabil.Api.Modules.Shared.Domain;
using CentralContabil.Api.Modules.Integrations.Domain;
using CentralContabil.Api.Modules.Knowledge.Domain;
using CentralContabil.Api.Modules.AI.Domain;
using CentralContabil.Api.Modules.Finance.Domain;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace CentralContabil.Api.Infrastructure;

public sealed class AppDbContext(DbContextOptions<AppDbContext> options)
    : IdentityDbContext<ApplicationUser, IdentityRole<Guid>, Guid>(options)
{
    public DbSet<Category> Categories => Set<Category>();
    public DbSet<Article> Articles => Set<Article>();
    public DbSet<ArticleVersion> ArticleVersions => Set<ArticleVersion>();
    public DbSet<Source> Sources => Set<Source>();
    public DbSet<LegalReference> LegalReferences => Set<LegalReference>();
    public DbSet<Calculator> Calculators => Set<Calculator>();
    public DbSet<CalculationRuleSet> CalculationRuleSets => Set<CalculationRuleSet>();
    public DbSet<RuleParameter> RuleParameters => Set<RuleParameter>();
    public DbSet<CalculationRun> CalculationRuns => Set<CalculationRun>();
    public DbSet<Favorite> Favorites => Set<Favorite>();
    public DbSet<PrivacyConsent> PrivacyConsents => Set<PrivacyConsent>();
    public DbSet<AuditLog> AuditLogs => Set<AuditLog>();
    public DbSet<RefreshToken> RefreshTokens => Set<RefreshToken>();
    public DbSet<ExternalProvider> ExternalProviders => Set<ExternalProvider>();
    public DbSet<ExternalEntitySnapshot> ExternalEntitySnapshots => Set<ExternalEntitySnapshot>();
    public DbSet<KnowledgeDocument> KnowledgeDocuments => Set<KnowledgeDocument>();
    public DbSet<KnowledgeChunk> KnowledgeChunks => Set<KnowledgeChunk>();
    public DbSet<AIRequest> AIRequests => Set<AIRequest>();
    public DbSet<UnansweredQuestion> UnansweredQuestions => Set<UnansweredQuestion>();
    public DbSet<FinancialCategory> FinancialCategories => Set<FinancialCategory>();
    public DbSet<FinancialTransaction> FinancialTransactions => Set<FinancialTransaction>();
    public DbSet<FinancialRecurrence> FinancialRecurrences => Set<FinancialRecurrence>();
    public DbSet<FinancialCategoryPreference> FinancialCategoryPreferences => Set<FinancialCategoryPreference>();
    public DbSet<MonthlyBudget> MonthlyBudgets => Set<MonthlyBudget>();
    public DbSet<FinancialGoal> FinancialGoals => Set<FinancialGoal>();
    public DbSet<FinancialGoalContribution> FinancialGoalContributions => Set<FinancialGoalContribution>();
    public DbSet<FinancialInstallmentPlan> FinancialInstallmentPlans => Set<FinancialInstallmentPlan>();
    public DbSet<CreditCard> CreditCards => Set<CreditCard>();
    public DbSet<FinancialAccount> FinancialAccounts => Set<FinancialAccount>();
    public DbSet<ScheduledTransaction> ScheduledTransactions => Set<ScheduledTransaction>();
    public DbSet<Debt> Debts => Set<Debt>();
    public DbSet<EmergencyReserve> EmergencyReserves => Set<EmergencyReserve>();
    public DbSet<UserPreference> UserPreferences => Set<UserPreference>();
    public DbSet<AssistantConversation> AssistantConversations => Set<AssistantConversation>();
    public DbSet<AssistantMessage> AssistantMessages => Set<AssistantMessage>();

    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);
        builder.HasDefaultSchema("central");
        builder.Entity<Category>().HasIndex(x => x.Slug).IsUnique();
        builder.Entity<Article>().HasIndex(x => x.Slug).IsUnique();
        builder.Entity<Calculator>().HasIndex(x => x.Slug).IsUnique();
        builder.Entity<ArticleVersion>().HasIndex(x => new { x.ArticleId, x.Version }).IsUnique();
        builder.Entity<ArticleSource>().HasKey(x => new { x.ArticleId, x.SourceId });
        builder.Entity<ArticleLegalReference>().HasKey(x => new { x.ArticleId, x.LegalReferenceId });
        builder.Entity<Article>().HasMany(x => x.ArticleSources).WithOne(x => x.Article).HasForeignKey(x => x.ArticleId);
        builder.Entity<Article>().HasMany(x => x.LegalReferences).WithOne(x => x.Article).HasForeignKey(x => x.ArticleId);
        builder.Entity<Favorite>().HasIndex(x => new { x.UserId, x.ArticleId }).IsUnique();
        builder.Entity<CalculationRuleSet>().HasIndex(x => new { x.CalculatorId, x.Version }).IsUnique();
        builder.Entity<RuleParameter>().HasIndex(x => new { x.RuleSetId, x.Key }).IsUnique();
        builder.Entity<CalculationRun>().Property(x => x.ResultAmount).HasPrecision(18, 2);
        builder.Entity<AuditLog>().Property(x => x.OldValues).HasColumnType("jsonb");
        builder.Entity<AuditLog>().Property(x => x.NewValues).HasColumnType("jsonb");
        builder.Entity<CalculationRun>().Property(x => x.InputJson).HasColumnType("jsonb");
        builder.Entity<CalculationRun>().Property(x => x.ResultJson).HasColumnType("jsonb");
        builder.Entity<ExternalProvider>().HasIndex(x => x.Name).IsUnique();
        builder.Entity<ExternalEntitySnapshot>().HasIndex(x => new { x.Provider, x.EntityType, x.ExternalKey }).IsUnique();
        builder.Entity<ExternalEntitySnapshot>().HasIndex(x => x.ExpiresAt);
        builder.Entity<ExternalEntitySnapshot>().Property(x => x.PayloadJson).HasColumnType("jsonb");
        builder.Entity<KnowledgeDocument>().HasIndex(x => x.ContentHash);
        builder.Entity<KnowledgeDocument>().HasIndex(x => new { x.Status, x.ValidFrom, x.ValidUntil });
        builder.Entity<KnowledgeDocument>().HasIndex(x => x.ArticleId).IsUnique().HasFilter("\"ArticleId\" IS NOT NULL");
        builder.Entity<KnowledgeChunk>().HasIndex(x => new { x.KnowledgeDocumentId, x.ChunkIndex }).IsUnique();
        builder.Entity<KnowledgeChunk>().HasIndex(x => new { x.EmbeddingProvider, x.EmbeddingModel, x.EmbeddingDimensions });
        builder.Entity<KnowledgeChunk>().Property(x => x.EmbeddingProvider).HasMaxLength(32);
        builder.Entity<KnowledgeChunk>().Property(x => x.EmbeddingModel).HasMaxLength(120);
        builder.Entity<KnowledgeDocument>().HasMany(x => x.Chunks).WithOne(x => x.KnowledgeDocument).HasForeignKey(x => x.KnowledgeDocumentId).OnDelete(DeleteBehavior.Cascade);
        builder.Entity<AIRequest>().HasIndex(x => x.CreatedAt);
        builder.Entity<UnansweredQuestion>().HasIndex(x => x.NormalizedQuestion).IsUnique();
        builder.Entity<FinancialCategory>().Property(x => x.Name).HasMaxLength(80);
        builder.Entity<FinancialCategory>().Property(x => x.Icon).HasMaxLength(40);
        builder.Entity<FinancialCategory>().HasIndex(x => new { x.UserId, x.Type, x.Name }).IsUnique();
        builder.Entity<FinancialCategory>().HasIndex(x => new { x.Type, x.IsActive });
        builder.Entity<FinancialCategory>().HasData(FinancialDefaultCategories.All);
        builder.Entity<FinancialTransaction>().Property(x => x.Description).HasMaxLength(160);
        builder.Entity<FinancialTransaction>().Property(x => x.Notes).HasMaxLength(1000);
        builder.Entity<FinancialTransaction>().Property(x => x.Amount).HasPrecision(18, 2);
        builder.Entity<FinancialTransaction>().ToTable(table => table.HasCheckConstraint("CK_FinancialTransactions_Amount_Positive", "\"Amount\" > 0"));
        builder.Entity<FinancialTransaction>().HasIndex(x => x.UserId);
        builder.Entity<FinancialTransaction>().HasIndex(x => x.CategoryId);
        builder.Entity<FinancialTransaction>().HasIndex(x => new { x.UserId, x.TransactionDate });
        builder.Entity<FinancialTransaction>().HasIndex(x => new { x.RecurrenceId, x.TransactionDate }).IsUnique().HasFilter("\"RecurrenceId\" IS NOT NULL");
        builder.Entity<FinancialTransaction>().HasOne(x => x.Category).WithMany().HasForeignKey(x => x.CategoryId).OnDelete(DeleteBehavior.Restrict);
        builder.Entity<FinancialTransaction>().HasOne(x => x.Recurrence).WithMany(x => x.Transactions).HasForeignKey(x => x.RecurrenceId).OnDelete(DeleteBehavior.SetNull);
        builder.Entity<FinancialRecurrence>().Property(x => x.Description).HasMaxLength(160);
        builder.Entity<FinancialRecurrence>().Property(x => x.Notes).HasMaxLength(1000);
        builder.Entity<FinancialRecurrence>().Property(x => x.Amount).HasPrecision(18, 2);
        builder.Entity<FinancialRecurrence>().ToTable(table => table.HasCheckConstraint("CK_FinancialRecurrences_Amount_Positive", "\"Amount\" > 0"));
        builder.Entity<FinancialRecurrence>().HasIndex(x => new { x.UserId, x.IsActive, x.NextOccurrence });
        builder.Entity<FinancialRecurrence>().HasOne(x => x.Category).WithMany().HasForeignKey(x => x.CategoryId).OnDelete(DeleteBehavior.Restrict);
        builder.Entity<FinancialCategoryPreference>().Property(x => x.NormalizedText).HasMaxLength(180);
        builder.Entity<FinancialCategoryPreference>().HasIndex(x => new { x.UserId, x.Type, x.NormalizedText }).IsUnique();
        builder.Entity<FinancialCategoryPreference>().HasOne(x => x.Category).WithMany().HasForeignKey(x => x.CategoryId).OnDelete(DeleteBehavior.Cascade);
        builder.Entity<FinancialTransaction>().HasIndex(x => new { x.InstallmentPlanId, x.InstallmentNumber }).IsUnique().HasFilter("\"InstallmentPlanId\" IS NOT NULL");
        builder.Entity<FinancialTransaction>().HasOne(x => x.InstallmentPlan).WithMany(x => x.Transactions).HasForeignKey(x => x.InstallmentPlanId).OnDelete(DeleteBehavior.Restrict);
        builder.Entity<MonthlyBudget>().Property(x => x.PlannedAmount).HasPrecision(18, 2);
        builder.Entity<MonthlyBudget>().ToTable(table => table.HasCheckConstraint("CK_MonthlyBudgets_PlannedAmount_Positive", "\"PlannedAmount\" > 0"));
        builder.Entity<MonthlyBudget>().HasIndex(x => new { x.UserId, x.CategoryId, x.Year, x.Month }).IsUnique();
        builder.Entity<MonthlyBudget>().HasOne(x => x.Category).WithMany().HasForeignKey(x => x.CategoryId).OnDelete(DeleteBehavior.Restrict);
        builder.Entity<FinancialGoal>().Property(x => x.Name).HasMaxLength(100);
        builder.Entity<FinancialGoal>().Property(x => x.Description).HasMaxLength(500);
        builder.Entity<FinancialGoal>().Property(x => x.TargetAmount).HasPrecision(18, 2);
        builder.Entity<FinancialGoal>().Property(x => x.CurrentAmount).HasPrecision(18, 2);
        builder.Entity<FinancialGoal>().ToTable(table => table.HasCheckConstraint("CK_FinancialGoals_Amounts", "\"TargetAmount\" > 0 AND \"CurrentAmount\" >= 0"));
        builder.Entity<FinancialGoal>().HasIndex(x => new { x.UserId, x.IsCompleted });
        builder.Entity<FinancialGoalContribution>().Property(x => x.Amount).HasPrecision(18, 2);
        builder.Entity<FinancialGoalContribution>().Property(x => x.Description).HasMaxLength(200);
        builder.Entity<FinancialGoalContribution>().ToTable(table => table.HasCheckConstraint("CK_FinancialGoalContributions_Amount_Positive", "\"Amount\" > 0"));
        builder.Entity<FinancialGoalContribution>().HasIndex(x => new { x.UserId, x.Date });
        builder.Entity<FinancialGoalContribution>().HasOne(x => x.Goal).WithMany(x => x.Contributions).HasForeignKey(x => x.GoalId).OnDelete(DeleteBehavior.Cascade);
        builder.Entity<FinancialInstallmentPlan>().Property(x => x.Description).HasMaxLength(160);
        builder.Entity<FinancialInstallmentPlan>().Property(x => x.TotalAmount).HasPrecision(18, 2);
        builder.Entity<FinancialInstallmentPlan>().ToTable(table => table.HasCheckConstraint("CK_FinancialInstallmentPlans_Values", "\"TotalAmount\" > 0 AND \"InstallmentCount\" >= 2"));
        builder.Entity<FinancialInstallmentPlan>().HasIndex(x => new { x.UserId, x.FirstDueDate });
        builder.Entity<FinancialInstallmentPlan>().HasOne(x => x.Category).WithMany().HasForeignKey(x => x.CategoryId).OnDelete(DeleteBehavior.Restrict);

        builder.Entity<CreditCard>().Property(x => x.Name).HasMaxLength(100);
        builder.Entity<CreditCard>().Property(x => x.Bank).HasMaxLength(100);
        builder.Entity<CreditCard>().Property(x => x.Last4).HasMaxLength(4);
        builder.Entity<CreditCard>().Property(x => x.Color).HasMaxLength(20);
        builder.Entity<CreditCard>().Property(x => x.Limit).HasPrecision(18, 2);
        builder.Entity<CreditCard>().ToTable(table => table.HasCheckConstraint("CK_CreditCards_Values", "\"Limit\" >= 0 AND \"ClosingDay\" BETWEEN 1 AND 31 AND \"DueDay\" BETWEEN 1 AND 31"));
        builder.Entity<CreditCard>().HasIndex(x => new { x.UserId, x.IsActive });
        builder.Entity<FinancialAccount>().Property(x => x.Name).HasMaxLength(100);
        builder.Entity<FinancialAccount>().Property(x => x.Color).HasMaxLength(20);
        builder.Entity<FinancialAccount>().Property(x => x.Balance).HasPrecision(18, 2);
        builder.Entity<FinancialAccount>().HasIndex(x => new { x.UserId, x.IsActive });
        builder.Entity<FinancialTransaction>().HasOne(x => x.CreditCard).WithMany(x => x.Transactions).HasForeignKey(x => x.CreditCardId).OnDelete(DeleteBehavior.SetNull);
        builder.Entity<FinancialTransaction>().HasOne(x => x.Account).WithMany(x => x.Transactions).HasForeignKey(x => x.AccountId).OnDelete(DeleteBehavior.SetNull);
        builder.Entity<ScheduledTransaction>().Property(x => x.Description).HasMaxLength(160);
        builder.Entity<ScheduledTransaction>().Property(x => x.Notes).HasMaxLength(1000);
        builder.Entity<ScheduledTransaction>().Property(x => x.Amount).HasPrecision(18, 2);
        builder.Entity<ScheduledTransaction>().ToTable(table => table.HasCheckConstraint("CK_ScheduledTransactions_Amount_Positive", "\"Amount\" > 0"));
        builder.Entity<ScheduledTransaction>().HasIndex(x => new { x.UserId, x.DueDate });
        builder.Entity<ScheduledTransaction>().HasIndex(x => new { x.UserId, x.Status });
        builder.Entity<ScheduledTransaction>().HasOne(x => x.Category).WithMany().HasForeignKey(x => x.CategoryId).OnDelete(DeleteBehavior.Restrict);
        builder.Entity<ScheduledTransaction>().HasOne(x => x.Account).WithMany().HasForeignKey(x => x.AccountId).OnDelete(DeleteBehavior.SetNull);
        builder.Entity<Debt>().Property(x => x.Name).HasMaxLength(100);
        builder.Entity<Debt>().Property(x => x.Institution).HasMaxLength(100);
        builder.Entity<Debt>().Property(x => x.Notes).HasMaxLength(1000);
        builder.Entity<Debt>().Property(x => x.OriginalAmount).HasPrecision(18, 2);
        builder.Entity<Debt>().Property(x => x.CurrentAmount).HasPrecision(18, 2);
        builder.Entity<Debt>().Property(x => x.InterestRate).HasPrecision(9, 4);
        builder.Entity<Debt>().ToTable(table => table.HasCheckConstraint("CK_Debts_Values", "\"OriginalAmount\" > 0 AND \"CurrentAmount\" >= 0"));
        builder.Entity<Debt>().HasIndex(x => new { x.UserId, x.IsPaid });
        builder.Entity<EmergencyReserve>().Property(x => x.TargetAmount).HasPrecision(18, 2);
        builder.Entity<EmergencyReserve>().Property(x => x.CurrentAmount).HasPrecision(18, 2);
        builder.Entity<EmergencyReserve>().Property(x => x.Notes).HasMaxLength(1000);
        builder.Entity<EmergencyReserve>().ToTable(table => table.HasCheckConstraint("CK_EmergencyReserves_Values", "\"TargetAmount\" > 0 AND \"CurrentAmount\" >= 0"));
        builder.Entity<EmergencyReserve>().HasIndex(x => x.UserId).IsUnique();
        builder.Entity<UserPreference>().HasIndex(x => x.UserId).IsUnique();
        builder.Entity<AssistantConversation>().Property(x => x.Title).HasMaxLength(200);
        builder.Entity<AssistantConversation>().HasIndex(x => new { x.UserId, x.CreatedAt });
        builder.Entity<AssistantConversation>().HasMany(x => x.Messages).WithOne(x => x.Conversation).HasForeignKey(x => x.ConversationId).OnDelete(DeleteBehavior.Cascade);
        builder.Entity<AssistantMessage>().Property(x => x.Role).HasMaxLength(20);
        builder.Entity<AssistantMessage>().Property(x => x.Content).HasMaxLength(20000);
        builder.Entity<AssistantMessage>().Property(x => x.SourcesJson).HasMaxLength(8000);
        builder.Entity<AssistantMessage>().HasIndex(x => new { x.ConversationId, x.CreatedAt });
    }
}
