import { Component, inject } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { FinanceQuickAccessComponent } from '../finance/finance-quick-access.component';
@Component({standalone:true,imports:[FormsModule,RouterLink,FinanceQuickAccessComponent],template:`
<section class="hero"><span class="eyebrow">CONTABILIDADE E FINANÇAS SEM COMPLICAÇÃO</span><h1>Entenda. Calcule.<br><em>Confira a fonte.</em></h1><p>Informação organizada, consultas públicas e ferramentas transparentes para decisões mais seguras.</p><form (ngSubmit)="search()" class="hero-search"><label for="q">O que você precisa resolver hoje?</label><div><input id="q" name="q" [(ngModel)]="query" placeholder="Assunto, CNPJ, NCM, lei ou projeto" required><button>Pesquisar</button></div></form></section>
<app-finance-quick-access/>
<section class="section"><div class="section-head"><div><span class="eyebrow">CONSULTAS V2</span><h2>Dados públicos em um só lugar</h2></div><span>Origem, atualização e cache sempre identificados.</span></div><div class="cards"><a routerLink="/empresas"><b>Empresas e CNPJ</b><span>CNPJ numérico e alfanumérico com dados cadastrais.</span><i>Consultar →</i></a><a routerLink="/ncm"><b>Tabela NCM</b><span>Busque por código ou descrição da mercadoria.</span><i>Pesquisar →</i></a><a routerLink="/buscar"><b>Busca universal</b><span>Conteúdo interno, legislação, proposições e integrações.</span><i>Buscar →</i></a></div></section>
<section class="section"><div class="section-head"><div><span class="eyebrow">FERRAMENTAS</span><h2>Calculadoras populares</h2></div><span>Resultado detalhado, fórmula e regra utilizada.</span></div><div class="cards tools"><a routerLink="/calculadoras/ferias"><b>Férias</b><span>Estime remuneração e abono</span><i>Calcular →</i></a><a routerLink="/calculadoras/decimo-terceiro"><b>13º salário</b><span>Calcule o valor proporcional</span><i>Calcular →</i></a><a routerLink="/calculadoras/juros-compostos"><b>Juros compostos</b><span>Projete investimentos e aportes</span><i>Calcular →</i></a></div></section>
<section class="trust"><div><span class="eyebrow">NOSSO COMPROMISSO</span><h2>Clareza em cada etapa</h2></div><div><b>01 · Entenda</b><p>Explicação simples e técnica, no seu ritmo.</p></div><div><b>02 · Calcule</b><p>Fórmulas transparentes e detalhamento completo.</p></div><div><b>03 · Confira</b><p>Fontes, vigência e versão da regra sempre visíveis.</p></div></section>`})
export class HomeComponent{private router=inject(Router);query='';search(){if(this.query.trim())void this.router.navigate(['/buscar'],{queryParams:{q:this.query.trim()}})}}
